<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Excubo.Blazor.Canvas" Version="3.2.66" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.11" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dgl\dgl.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="d9.aoc.core">
      <HintPath>..\..\..\aoc\src\core\bin\Release\net8.0\d9.aoc.core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
